# Generated by Django 5.0.1 on 2026-01-26 09:28

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0013_googlecompany'),
        ('job_utility', '0001_initial'),
        ('utility', '0004_alter_city_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], max_length=20)),
                ('work_location_type', models.CharField(choices=[('office', 'Work from Office'), ('field', 'Field Job'), ('home', 'Work from Home')], max_length=20)),
                ('gender', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('min_experience_months', models.PositiveIntegerField(default=0)),
                ('max_experience_months', models.PositiveIntegerField(default=0)),
                ('only_fresher', models.BooleanField(default=False)),
                ('salary_min', models.PositiveIntegerField()),
                ('salary_max', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('requirements', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assets', models.ManyToManyField(blank=True, to='job_utility.jobasset')),
                ('benefits', models.ManyToManyField(blank=True, to='job_utility.jobbenefit')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_utility.jobcategory')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='business.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, to='job_utility.jobdocument')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_utility.jobindustry')),
                ('languages', models.ManyToManyField(blank=True, to='job_utility.joblanguagerequirement')),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.locality')),
                ('salary_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_utility.salarytype')),
                ('skills', models.ManyToManyField(blank=True, to='job_utility.jobskill')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_utility.jobtitle')),
                ('working_days', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_utility.workingdaysoption')),
            ],
        ),
    ]
