# Generated by Django 5.0.1 on 2026-06-07 10:38

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('job_utility', '0001_initial'),
        ('response', '0001_initial'),
        ('utility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sales / Pre-Sales', 'Sales / Pre-Sales'), ('Telesales', 'Telesales'), ('Field Sales', 'Field Sales'), ('Customer Suppor', 'Customer Suppor')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], max_length=20)),
                ('work_location_type', models.CharField(choices=[('office', 'Office'), ('field', 'Field'), ('home', 'Work From Home')], default='office', max_length=20)),
                ('gender', models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10)),
                ('min_experience_months', models.PositiveIntegerField(default=0)),
                ('max_experience_months', models.PositiveIntegerField(default=0)),
                ('salary_type', models.CharField(choices=[('fixed', 'Fixed'), ('fixed_incentive', 'Fixed + Incentive'), ('commission', 'Commission')], default='fixed', max_length=30)),
                ('salary_min', models.PositiveIntegerField()),
                ('salary_max', models.PositiveIntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('requirements', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assets', models.ManyToManyField(blank=True, to='job_utility.jobasset')),
                ('benefits', models.ManyToManyField(blank=True, to='job_utility.jobbenefit')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='business.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, to='job_utility.jobdocument')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_utility.jobindustry')),
                ('languages', models.ManyToManyField(blank=True, to='job_utility.joblanguagerequirement')),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.locality')),
                ('skills', models.ManyToManyField(blank=True, to='job_utility.jobskill')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_utility.jobtitle')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_updated', to=settings.AUTH_USER_MODEL)),
                ('working_days', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_utility.workingdaysoption')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('experience_months', models.PositiveIntegerField(default=0)),
                ('current_company', models.CharField(blank=True, max_length=150, null=True)),
                ('current_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('notice_period', models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('45_days', '45 Days'), ('60_days', '60 Days')], max_length=20, null=True)),
                ('expected_joining_date', models.DateField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('apply_source', models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('call', 'Call'), ('admin', 'Admin'), ('import', 'Imported')], default='website', max_length=20)),
                ('allow_whatsapp', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('applied', 'New Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('Switched Off', 'Switched Off'), ('Call Tomorrow', 'Call Tomorrow'), ('Not_received', 'Not Received'), ('Not Interested', 'Not Interested'), ('Call later', 'Call later'), ('Not Interested', 'Not Interested')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.locality')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('interview_type', models.CharField(choices=[('telephonic', 'Telephonic'), ('video', 'Video Call'), ('face_to_face', 'Face to Face'), ('hr_round', 'HR Round'), ('technical', 'Technical Round'), ('final', 'Final Round')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('rescheduled_from', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('follow_up', 'Follow Up Required')], default='scheduled', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('internal_feedback', models.TextField(blank=True, null=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('confirmation_received', models.BooleanField(default=False)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='response.staff')),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='jobs.jobapplicant')),
            ],
        ),
    ]
