# Generated by Django 5.0.1 on 2026-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('fixed', 'Fixed Salary'), ('fixed_incentive', 'Fixed + Incentives'), ('commission', 'Commission Based')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
