# Generated by Django 6.0.6 on 2026-06-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_images/'),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='other_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='apply_source',
            field=models.CharField(choices=[('Apna', 'Apna'), ('Job_hai', 'Job Hai'), ('Indeed', 'Indeed'), ('Work_India', 'Work India'), ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('call', 'Call'), ('admin', 'Admin'), ('import', 'Imported')], default='website', max_length=20),
        ),
    ]
