# Generated by Django 6.0.6 on 2026-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplicant_image_jobapplicant_other_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='data_source',
            field=models.CharField(choices=[('Apply', 'Apply'), ('Recommendations', 'Recommendations'), ('Data_Base', 'Data Base')], default='Apply', max_length=20),
        ),
    ]
