# Generated by Django 5.0.1 on 2026-01-26 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_utility', '0001_initial'),
        ('jobs', '0002_alter_job_salary_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_utility.jobtitle'),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_location_type',
            field=models.CharField(blank=True, choices=[('office', 'Work from Office'), ('field', 'Field Job'), ('home', 'Work from Home')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='working_days',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_utility.workingdaysoption'),
        ),
    ]
