# Generated by Django 5.0.1 on 2026-01-26 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_utility', '0001_initial'),
        ('jobs', '0003_alter_job_created_by_alter_job_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('fixed', 'Fixed Salary'), ('fixed_incentive', 'Fixed + Incentives'), ('commission', 'Commission Based')], default='fixed', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_utility.jobtitle'),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_location_type',
            field=models.CharField(choices=[('office', 'Work from Office'), ('field', 'Field Job'), ('home', 'Work from Home')], default='office', max_length=20),
        ),
    ]
