# Generated by Django 5.0.1 on 2026-01-26 13:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_only_fresher_job_updated_by_and_more'),
        ('response', '0005_response_converted_at_response_is_converted_and_more'),
        ('utility', '0004_alter_city_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('experience_months', models.PositiveIntegerField(default=0)),
                ('current_company', models.CharField(blank=True, max_length=150)),
                ('current_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('notice_period', models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('45_days', '45 Days'), ('60_days', '60 Days')], max_length=20)),
                ('expected_joining_date', models.DateField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('apply_source', models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('call', 'Call'), ('admin', 'Admin'), ('import', 'Imported')], default='website', max_length=20)),
                ('allow_whatsapp', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('applied', 'New Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.locality')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('telephonic', 'Telephonic'), ('video', 'Video Call'), ('face_to_face', 'Face to Face')], default='telephonic', max_length=20)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='response.staff')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='jobs.jobapplicant')),
            ],
        ),
    ]
