# Generated by Django 5.0.1 on 2026-01-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobapplicant_interviewschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_type',
            field=models.CharField(choices=[('telephonic', 'Telephonic'), ('video', 'Video Call'), ('face_to_face', 'Face to Face')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
