# Generated by Django 5.0.1 on 2026-01-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_interviewschedule_job_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Sales / Pre-Sales', 'Sales / Pre-Sales'), ('Telesales', 'Telesales'), ('Field Sales', 'Field Sales'), ('Customer Suppor', 'Customer Suppor')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
