# Generated by Django 5.0.1 on 2026-01-29 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_jobapplicant_city_and_more'),
        ('response', '0005_response_converted_at_response_is_converted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewschedule',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='interviewschedule',
            name='interview_time',
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='confirmation_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='internal_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='next_followup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='rescheduled_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='scheduled_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='response.staff'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_type',
            field=models.CharField(choices=[('telephonic', 'Telephonic'), ('video', 'Video Call'), ('face_to_face', 'Face to Face'), ('hr_round', 'HR Round'), ('technical', 'Technical Round'), ('final', 'Final Round')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('follow_up', 'Follow Up Required')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='status',
            field=models.CharField(choices=[('applied', 'New Applied'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('Switched Off', 'Switched Off'), ('Call Tomorrow', 'Call Tomorrow'), ('Not_received', 'Not Received'), ('Not Interested', 'Not Interested'), ('Call later', 'Call later'), ('Not Interested', 'Not Interested')], default='applied', max_length=20),
        ),
    ]
