# Generated by Django 5.0.1 on 2026-05-07 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumbai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mumbairesponse',
            options={'ordering': ['-create_at'], 'verbose_name': 'Mumbai Company', 'verbose_name_plural': '2. Response'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mumbai_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='mumbai.mumbaicompany'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='real_estate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='mumbai.mumbairealestategmb'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='mumbai.mumbairesponse'),
        ),
        migrations.AlterField(
            model_name='mumbaicompany',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('FollowUp', 'Follow Up'), ('Not_received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number'), ('Meeting_FollowUp', 'Meeting-Follow Up')], default='New', max_length=25),
        ),
        migrations.AlterField(
            model_name='mumbairealestategmb',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('FollowUp', 'Follow Up'), ('Call_Cut', 'Call Cut'), ('Not Received', 'Not Received'), ('Not Interested', 'Not Interested'), ('Deal Done', 'Deal Done'), ('Meeting_FollowUp', 'Meeting-Follow Up')], default='New', max_length=25),
        ),
    ]
