# Generated by Django 5.0.1 on 2026-05-23 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumbai', '0002_alter_mumbairesponse_options_and_more'),
        ('projects', '0001_initial'),
        ('utility', '0006_alter_city_is_top_cities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mumbaicompany',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '1.Company'},
        ),
        migrations.AlterModelOptions(
            name='mumbairealestategmb',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '3. Real Estate'},
        ),
        migrations.AlterModelOptions(
            name='mumbairesponse',
            options={'ordering': ['-create_at'], 'verbose_name_plural': '2. Response'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company'), ('Real_Estate', 'Real Estate'), ('Refrense', 'Refrense')], default='Response', max_length=20),
        ),
        migrations.AlterField(
            model_name='followup',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company'), ('Real_Estate', 'Real Estate'), ('Refrense', 'Refrense')], default='Response', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company'), ('Real_Estate', 'Real Estate'), ('Refrense', 'Refrense')], default='Response', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company'), ('Real_Estate', 'Real Estate'), ('Refrense', 'Refrense')], default='Response', max_length=20),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company'), ('Real_Estate', 'Real Estate'), ('Refrense', 'Refrense')], default='Response', max_length=20),
        ),
        migrations.CreateModel(
            name='Refrense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('FollowUp', 'Follow Up'), ('Not_received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number'), ('Meeting_FollowUp', 'Meeting-Follow Up')], default='New', max_length=25)),
                ('refrense_name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('google_map', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('business_status_raw', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='refrense/logo/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrense_assigned', to='mumbai.staff')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrense_categories', to='utility.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrense_created', to=settings.AUTH_USER_MODEL)),
                ('googlemap_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrense_googlemap_status', to='utility.googlemap_status')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refrense_localities', to='utility.locality')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrense_projects', to='projects.project')),
                ('sub_locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrense_sublocalities', to='utility.sub_locality')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrense_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '4. Refrense',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='refrense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mumbai.refrense'),
        ),
        migrations.AddField(
            model_name='followup',
            name='refrense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='mumbai.refrense'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='refrense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='mumbai.refrense'),
        ),
        migrations.AddField(
            model_name='visit',
            name='refrense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='mumbai.refrense'),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='refrense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='mumbai.refrense'),
        ),
    ]
