# Generated by Django 5.0.1 on 2026-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumbai', '0003_alter_mumbaicompany_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrense',
            name='other_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
