# Generated by Django 5.0.1 on 2026-05-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumbai', '0004_refrense_other_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrense',
            name='other_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
