# Generated by Django 5.0.1 on 2026-06-28 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_architects_postal_code_developer_postal_code_and_more'),
        ('utility', '0003_alter_postal_code_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architects',
            options={'ordering': ['-create_at'], 'verbose_name_plural': '2. Architects'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['-create_at'], 'verbose_name_plural': '1. Developer'},
        ),
        migrations.AlterModelOptions(
            name='engineer',
            options={'ordering': ['-create_at'], 'verbose_name_plural': '3. Engineer'},
        ),
        migrations.AddField(
            model_name='architects',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='architect_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='architects',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='architect_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='architects',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='architects',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='architects',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='architects',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('FollowUp', 'Follow Up'), ('Meeting_FollowUp', 'Meeting-Follow Up'), ('Not Received', 'Not Received'), ('Not Interested', 'Not Interested'), ('Deal Done', 'Deal Done')], default='New', max_length=25),
        ),
        migrations.AddField(
            model_name='architects',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='architect_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developer',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developer',
            name='calling_status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Meeting', 'Meeting'), ('FollowUp', 'Follow Up'), ('Meeting_FollowUp', 'Meeting-Follow Up'), ('Not Received', 'Not Received'), ('Not Interested', 'Not Interested'), ('Deal Done', 'Deal Done')], default='New', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engineer',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engineer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineer',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('FollowUp', 'Follow Up'), ('Meeting_FollowUp', 'Meeting-Follow Up'), ('Not Received', 'Not Received'), ('Not Interested', 'Not Interested'), ('Deal Done', 'Deal Done')], default='New', max_length=25),
        ),
        migrations.AddField(
            model_name='engineer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='calling_status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Meeting', 'Meeting'), ('FollowUp', 'Follow Up'), ('Meeting_FollowUp', 'Meeting-Follow Up'), ('Not Received', 'Not Received'), ('Not Interested', 'Not Interested'), ('Deal Done', 'Deal Done')], default='New', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='architects',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='architects',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='architect/logo/'),
        ),
        migrations.AlterField(
            model_name='architects',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.postal_code'),
        ),
        migrations.AlterField(
            model_name='architects',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='developer/logo/'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.postal_code'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='engineer/logo/'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.postal_code'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Architect', 'Architect'), ('Engineer', 'Engineer'), ('Project', 'Project')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='properties.architects')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_comments_created', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='properties.developer')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='properties.engineer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='properties.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Architect', 'Architect'), ('Engineer', 'Engineer'), ('Project', 'Project')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('New Followup', 'New Followup'), ('Re Followup', 'Re Followup'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], default='New Followup', max_length=25)),
                ('followup_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('architect', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='properties.architects')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_followup_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_followup_created', to=settings.AUTH_USER_MODEL)),
                ('developer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='properties.developer')),
                ('engineer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='properties.engineer')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='properties.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Architect', 'Architect'), ('Engineer', 'Engineer'), ('Project', 'Project')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('New Meeting', 'New Meeting'), ('Re Meeting', 'Re Meeting'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], default='New Meeting', max_length=25)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('architect', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='properties.architects')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_meeting_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_meeting_created', to=settings.AUTH_USER_MODEL)),
                ('developer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='properties.developer')),
                ('engineer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='properties.engineer')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='properties.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_contact_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='properties.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Contact',
                'verbose_name_plural': 'Project Contacts',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Architect', 'Architect'), ('Engineer', 'Engineer'), ('Project', 'Project')], max_length=20, null=True)),
                ('visit_for', models.CharField(choices=[('Meeting', 'Meeting'), ('Door To Door', 'Door To Door'), ('Site Visit', 'Site Visit'), ('Follow Up', 'Follow Up'), ('Negotiation', 'Negotiation')], max_length=50)),
                ('visit_type', models.CharField(choices=[('1st Visit', '1st Visit'), ('2nd Visit', '2nd Visit'), ('3rd Visit', '3rd Visit'), ('4th Visit', '4th Visit'), ('5th Visit', '5th Visit')], max_length=50)),
                ('visit_status', models.CharField(choices=[('Meeting', 'Meeting'), ('Interested', 'Interested'), ('Follow Up', 'Follow Up'), ('Deal Done', 'Deal Done'), ('Not Interested', 'Not Interested'), ('Owner Not Available', 'Owner Not Available')], max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.architects')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_visit_created', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.developer')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.engineer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Architect', 'Architect'), ('Engineer', 'Engineer'), ('Project', 'Project')], max_length=20, null=True)),
                ('file', models.FileField(upload_to='voice_recordings/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='properties.architects')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='properties.developer')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='properties.engineer')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='properties.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_voice_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
