# Generated by Django 5.0.1 on 2026-01-10 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
        ('response', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.AddField(
            model_name='googlecompany',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realestate_googlecompany_assigned', to='response.staff'),
        ),
        migrations.AddField(
            model_name='googlecompany',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realestate_googlecompany_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googlecompany',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='googlecompany',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlecompany',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlecompany',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='googlecompany',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow Up'), ('Not_received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number')], default='New', max_length=25),
        ),
        migrations.AddField(
            model_name='googlecompany',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realestate_googlecompany_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
