# Generated by Django 5.0.1 on 2026-01-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_rename_created_at_comment_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecompany',
            name='business_status',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='category_text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='cid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='place_id',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='street',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='type',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
