# Generated by Django 5.0.1 on 2026-01-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('realestate', '0003_alter_googlecompany_business_status_and_more'),
        ('utility', '0002_bank_possessionin_projectamenities_propertyamenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecompany',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utility.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googlecompany',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.locality'),
        ),
        migrations.AddField(
            model_name='googlecompany',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AddField(
            model_name='googlecompany',
            name='sub_locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.sub_locality'),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='business_status',
            field=models.CharField(blank=True, db_index=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='category_text',
            field=models.CharField(blank=True, db_index=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow Up'), ('Not_received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number'), ('Send Ditails', 'Send Ditails')], default='New', max_length=25),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='street',
            field=models.CharField(blank=True, db_index=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='website',
            field=models.CharField(blank=True, db_index=True, max_length=550, null=True),
        ),
    ]
