# Generated by Django 5.0.1 on 2026-01-12 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_googlecompany_city_googlecompany_locality_and_more'),
        ('utility', '0002_bank_possessionin_projectamenities_propertyamenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecompany',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.category'),
        ),
    ]
