# Generated by Django 5.0.1 on 2026-01-12 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_googlecompany_category'),
        ('utility', '0002_bank_possessionin_projectamenities_propertyamenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecompany',
            name='cid',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city'),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='city_text',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.locality'),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='googlecompany',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
