# Generated by Django 5.0.1 on 2026-01-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_alter_googlecompany_cid_alter_googlecompany_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlecompany',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '1. Google Companies'},
        ),
    ]
