# Generated by Django 5.0.1 on 2026-01-14 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name_plural': '0. Responses'},
        ),
        migrations.AlterModelOptions(
            name='voicerecording',
            options={},
        ),
    ]
