# Generated by Django 5.0.1 on 2026-01-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_alter_comment_options_alter_followup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='contact_no',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
    ]
