# Generated by Django 5.0.1 on 2026-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_alter_response_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='contact_no',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
    ]
