# Generated by Django 5.0.1 on 2026-01-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_alter_response_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='lead_source',
            field=models.CharField(choices=[('instagram', 'Instagram Ads'), ('facebook', 'Facebook Ads'), ('google', 'Google Ads'), ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('Just Dial', 'Just Dial'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='response',
            name='whatsapp_followup_1_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='whatsapp_followup_2_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='whatsapp_welcome_sent',
            field=models.BooleanField(default=False),
        ),
    ]
