# Generated by Django 5.0.1 on 2026-02-21 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0005_response_converted_at_response_is_converted_and_more'),
        ('utility', '0004_alter_city_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-followup_date']},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-meeting_date']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-create_at'], 'verbose_name_plural': '0. Responses'},
        ),
        migrations.AlterField(
            model_name='followup',
            name='followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('New Followup', 'New Followup'), ('Re Followup', 'Re Followup'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], max_length=25),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('New Meeting', 'New Meeting'), ('Re Meeting', 'Re Meeting'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], max_length=25),
        ),
        migrations.AlterField(
            model_name='response',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_responses', to='response.staff'),
        ),
        migrations.AlterField(
            model_name='response',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.category'),
        ),
        migrations.AlterField(
            model_name='response',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.city'),
        ),
        migrations.AlterField(
            model_name='response',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.locality'),
        ),
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow Up'), ('Not_received', 'Not Received'), ('Software_company', 'Software Company'), ('For_job', 'For Job'), ('Training', 'Training'), ('Fake_lead', 'Fake Lead'), ('Deal_close', 'Deal Close')], db_index=True, default='New', max_length=25),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['contact_no'], name='response_re_contact_0846d3_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['status'], name='response_re_status_b9a6fd_idx'),
        ),
    ]
