# Generated by Django 6.0.6 on 2026-06-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_developer_alter_project_developer'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='land_parce',
            new_name='land_parcel',
        ),
        migrations.AlterField(
            model_name='project',
            name='possession_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.possessionin'),
        ),
    ]
