# Generated by Django 6.0.6 on 2026-06-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_land_parce_project_land_parcel_and_more'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='note',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Architects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('google_map', models.CharField(blank=True, max_length=1000)),
                ('web_site', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('about_architect', models.TextField(blank=True, max_length=5000, null=True)),
                ('note', models.TextField(blank=True, max_length=5000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('featured_architect', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
            ],
            options={
                'verbose_name_plural': 'Architects',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='architects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.architects'),
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('google_map', models.CharField(blank=True, max_length=1000)),
                ('web_site', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('about_engineer', models.TextField(blank=True, max_length=5000, null=True)),
                ('note', models.TextField(blank=True, max_length=5000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('featured_engineer', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
            ],
            options={
                'verbose_name_plural': 'Engineer',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.engineer'),
        ),
    ]
