# Generated by Django 6.0.6 on 2026-06-27 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_developer_note_alter_developer_logo_architects_and_more'),
        ('utility', '0002_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='architects',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.postal_code'),
        ),
        migrations.AddField(
            model_name='developer',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.postal_code'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.postal_code'),
        ),
        migrations.AddField(
            model_name='project',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.postal_code'),
        ),
    ]
