# Generated by Django 5.0.1 on 2026-06-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_architects_options_alter_developer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architects',
            old_name='status',
            new_name='calling_status',
        ),
        migrations.RenameField(
            model_name='engineer',
            old_name='status',
            new_name='calling_status',
        ),
    ]
