# Generated by Django 5.0.1 on 2026-06-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rename_status_architects_calling_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
