# Generated by Django 5.0.1 on 2026-06-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_developer_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architects',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
