# Generated by Django 5.0.1 on 2026-05-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahmedabad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahmedabadcompany',
            options={'ordering': ['-created_at'], 'verbose_name': '1. Company'},
        ),
        migrations.AlterModelOptions(
            name='ahmedabadrealestategmb',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '3. Real Estate'},
        ),
        migrations.AlterModelOptions(
            name='ahmedabadresponse',
            options={'ordering': ['-create_at'], 'verbose_name_plural': '2. Response'},
        ),
    ]
