# Generated by Django 5.0.1 on 2026-01-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='jobtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobtitle', to='job_utility.jobtitle'),
        ),
        migrations.AlterField(
            model_name='workingdaysoption',
            name='label',
            field=models.CharField(max_length=150),
        ),
    ]
