# Generated by Django 5.0.1 on 2026-01-29 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_utility', '0002_jobcategory_jobtitle_alter_workingdaysoption_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobskill',
            name='jobtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JobSkill', to='job_utility.jobtitle'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='jobtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JobCategory', to='job_utility.jobtitle'),
        ),
    ]
