# Generated by Django 5.0.1 on 2026-01-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtypms', '0002_alter_googlecompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecompany',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow Up', 'Follow Up'), ('Not Received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number'), ('Send Ditails', 'Send Ditails'), ('Deal Done', 'Deal Done')], default='New', max_length=25),
        ),
    ]
