# Generated by Django 5.0.1 on 2026-02-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtypms', '0003_alter_googlecompany_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('New Meeting', 'New Meeting'), ('Visit', 'Visit'), ('Re Meeting', 'Re Meeting'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], max_length=25),
        ),
    ]
