# Generated by Django 5.0.1 on 2025-12-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='sociallink',
            old_name='socia_site',
            new_name='social_site',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='company',
            name='total_reviews',
        ),
        migrations.AlterField(
            model_name='company',
            name='google_map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
