# Generated by Django 5.0.1 on 2025-12-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_company_options_rename_product_images_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
