# Generated by Django 5.0.1 on 2025-12-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_company_contact_no'),
        ('utility', '0002_bank_possessionin_projectamenities_propertyamenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utility.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='locality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utility.locality'),
            preserve_default=False,
        ),
    ]
