# Generated by Django 5.0.1 on 2025-12-28 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_company_city_alter_company_locality'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
