# Generated by Django 5.0.1 on 2026-01-07 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_company_project'),
        ('response', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': '1. Company'},
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['New Followup', 'Re Followup'])), fields=('company',), name='unique_active_followup_per_company'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['New Meeting', 'Re Meeting'])), fields=('company',), name='unique_active_meeting_per_company'),
        ),
    ]
