# Generated by Django 5.0.1 on 2026-01-07 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_company_options_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='voicerecording',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='meeting',
            name='unique_active_meeting_per_company',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='business.company'),
        ),
    ]
