# Generated by Django 5.0.1 on 2026-01-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_comment_options_alter_followup_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='followup',
            name='unique_active_followup_per_company',
        ),
        migrations.AlterField(
            model_name='followup',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='business.company'),
        ),
    ]
