# Generated by Django 5.0.1 on 2026-01-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_remove_followup_unique_active_followup_per_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='whatsapp',
        ),
    ]
