# Generated by Django 5.0.1 on 2026-01-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_company_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
