# Generated by Django 5.0.1 on 2026-01-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_alter_company_options_company_business_status_raw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_for_emails', models.CharField(blank=True, max_length=255, null=True)),
                ('category_text', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city_text', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cid', models.CharField(blank=True, max_length=255, null=True)),
                ('business_status', models.CharField(blank=True, max_length=255, null=True)),
                ('working_hours', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '0. Google Companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
