# Generated by Django 6.0.6 on 2026-06-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postal_code',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
