# Generated by Django 5.0.1 on 2026-01-12 15:36

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_bank_possessionin_projectamenities_propertyamenities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Location (City/Locality)', 'verbose_name_plural': 'Locations (Cities/Localities)'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='title',
        ),
        migrations.RemoveField(
            model_name='city',
            name='update_at',
        ),
        migrations.AddField(
            model_name='city',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='level_type',
            field=models.CharField(choices=[('STATE', 'State/Province'), ('CITY', 'City'), ('LOCALITY', 'Locality/Sector'), ('AREA', 'Sub-Area/Zone')], default='LOCALITY', max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='utility.city', verbose_name='Parent Location (State/City)'),
        ),
        migrations.AddField(
        model_name='city',
        name='rght',
        field=models.PositiveIntegerField(default=1, editable=False),

        preserve_default=False,
    ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
