# Generated by Django 5.0.1 on 2026-01-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_alter_city_options_remove_city_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
