# Generated by Django 5.0.1 on 2026-03-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_top_cities',
            field=models.BooleanField(default=False),
        ),
    ]
