# Generated by Django 5.0.1 on 2026-03-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0005_city_is_top_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='is_top_cities',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
