# Generated by Django 5.0.1 on 2026-05-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admedabad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahmedabadresponse',
            name='city',
        ),
        migrations.AddField(
            model_name='ahmedabadresponse',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('New Followup', 'New Followup'), ('Re Followup', 'Re Followup'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], max_length=25),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('New Meeting', 'New Meeting'), ('Visit', 'Visit'), ('Re Meeting', 'Re Meeting'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], default='New Meeting', max_length=25),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_for',
            field=models.CharField(choices=[('Telling Meeting', 'Telling Meeting'), ('Door To Door', 'Door To Door'), ('Site Visit', 'Site Visit'), ('Follow Up', 'Follow Up'), ('Negotiation', 'Negotiation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_status',
            field=models.CharField(choices=[('Deal_Close', 'Deal Close'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow Up'), ('Owner not In Office', 'Owner not In Office'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested')], max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('1st Visit', '1st Visit'), ('2nd Visit', '2nd Visit'), ('3rd Visit', '3rd Visit'), ('4th Visit', '4th Visit'), ('5th Visit', '5th Visit')], max_length=50),
        ),
    ]
