# Generated by Django 5.0.1 on 2026-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admedabad', '0002_remove_ahmedabadresponse_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='Followup_from',
            field=models.CharField(blank=True, choices=[('Response', 'Data_Calling'), ('Door_To_DooR', 'Data_Calling Ads'), ('Data_Calling', 'Data_Calling')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Followup_from',
            field=models.CharField(blank=True, choices=[('Response', 'Data_Calling'), ('Door_To_DooR', 'Data_Calling Ads'), ('Data_Calling', 'Data_Calling')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ahmedabadresponse',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting_FollowUp', 'Meeting / Follow Up'), ('Not_received', 'Not Received'), ('Software_company', 'Software Company'), ('For_job', 'For Job'), ('Training', 'Training'), ('Fake_lead', 'Fake Lead'), ('Deal_close', 'Deal Close')], default='New', max_length=25),
        ),
    ]
