# Generated by Django 5.0.1 on 2026-05-05 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admedabad', '0005_comment_form_type_comment_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='voicerecording',
            old_name='uploaded_at',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company')], default='Response', max_length=20),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='admedabad.ahmedabadresponse'),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='admedabad.ahmedabadcompany'),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
