# Generated by Django 5.0.1 on 2026-05-05 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admedabad', '0007_alter_voicerecording_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='uploaded_at',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='visit',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company')], default='Response', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='admedabad.ahmedabadresponse'),
        ),
        migrations.AddField(
            model_name='visit',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='admedabad.ahmedabadcompany'),
        ),
    ]
