# Generated by Django 5.0.1 on 2026-05-05 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admedabad', '0008_rename_uploaded_at_visit_create_at_visit_form_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='visit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
