# Generated by Django 5.0.1 on 2026-05-05 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admedabad', '0009_remove_visit_uploaded_by_visit_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='Followup_from',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='Followup_from',
        ),
        migrations.AddField(
            model_name='followup',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company')], default='Response', max_length=20),
        ),
        migrations.AddField(
            model_name='followup',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='admedabad.ahmedabadresponse'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company')], default='Response', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_from',
            field=models.CharField(blank=True, choices=[('Response', 'Data Calling'), ('Door_To_Door', 'Data Calling Ads'), ('Data_Calling', 'Data Calling')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='admedabad.ahmedabadresponse'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_assigned', to='admedabad.staff'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='admedabad.ahmedabadcompany'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_assigned', to='admedabad.staff'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='admedabad.ahmedabadcompany'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='followup_from',
            field=models.CharField(blank=True, choices=[('Response', 'Data Calling'), ('Door_To_Door', 'Data Calling Ads'), ('Data_Calling', 'Data Calling')], max_length=25, null=True),
        ),
    ]
