# Generated by Django 5.0.1 on 2026-05-05 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admedabad', '0010_remove_followup_followup_from_and_more'),
        ('utility', '0006_alter_city_is_top_cities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company'), ('Real_Estate', 'Real Estate')], default='Response', max_length=20),
        ),
        migrations.AlterField(
            model_name='followup',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company'), ('Real_Estate', 'Real Estate')], default='Response', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company'), ('Real_Estate', 'Real Estate')], default='Response', max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company'), ('Real_Estate', 'Real Estate')], default='Response', max_length=20),
        ),
        migrations.AlterField(
            model_name='voicerecording',
            name='form_type',
            field=models.CharField(choices=[('Response', 'Response'), ('Company', 'Company'), ('Real_Estate', 'Real Estate')], default='Response', max_length=20),
        ),
        migrations.CreateModel(
            name='AhmedabadRealEstateGMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_for_emails', models.CharField(blank=True, max_length=255, null=True)),
                ('category_text', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('city_text', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True)),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('cid', models.CharField(blank=True, db_index=True, max_length=300, null=True)),
                ('business_status', models.CharField(blank=True, db_index=True, max_length=550, null=True)),
                ('working_hours', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow Up', 'Follow Up'), ('Not Received', 'Not Received'), ('Not Interested', 'Not Interested'), ('Deal Done', 'Deal Done')], default='New', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_gmb_assigned', to='admedabad.staff')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_gmb_categories', to='utility.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_gmb_cities', to='utility.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_gmb_created', to=settings.AUTH_USER_MODEL)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_gmb_localities', to='utility.locality')),
                ('sub_locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_gmb_sublocalities', to='utility.sub_locality')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_gmb_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '0.Real Estate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='admedabad.ahmedabadrealestategmb'),
        ),
        migrations.AddField(
            model_name='followup',
            name='real_estate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='admedabad.ahmedabadrealestategmb'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='real_estate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='admedabad.ahmedabadrealestategmb'),
        ),
        migrations.AddField(
            model_name='visit',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='admedabad.ahmedabadrealestategmb'),
        ),
        migrations.AddField(
            model_name='voicerecording',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voices', to='admedabad.ahmedabadrealestategmb'),
        ),
    ]
