# Generated by Django 5.0.1 on 2026-05-06 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admedabad', '0011_alter_comment_form_type_alter_followup_form_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_from',
        ),
        migrations.AddField(
            model_name='followup',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='meeting_from',
            field=models.CharField(blank=True, choices=[('Response', 'Data Calling'), ('Door_To_Door', 'Data Calling Ads'), ('Data_Calling', 'Data Calling')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ahmedabadresponse',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('FollowUp', 'Follow Up'), ('Not_received', 'Not Received'), ('Software_company', 'Software Company'), ('For_job', 'For Job'), ('Training', 'Training'), ('Fake_lead', 'Fake Lead'), ('Deal_close', 'Deal Close'), ('Meeting_FollowUp', 'Meeting / Follow Up')], default='New', max_length=25),
        ),
        migrations.AlterField(
            model_name='followup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_assigned', to='admedabad.staff'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='admedabad.ahmedabadcompany'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_meeting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup',
            name='real_estate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='admedabad.ahmedabadrealestategmb'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='admedabad.ahmedabadresponse'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('New Meeting', 'New Meeting'), ('Visit', 'Visit'), ('Re Meeting', 'Re Meeting'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], default='New Meeting', max_length=25),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_staff_meetings', to='admedabad.staff'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ahmedabad_company_meetings', to='admedabad.ahmedabadcompany'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_user_created_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ahmedabad_realestate_meetings', to='admedabad.ahmedabadrealestategmb'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ahmedabad_response_meetings', to='admedabad.ahmedabadresponse'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('New Meeting', 'New Meeting'), ('Re Meeting', 'Re Meeting'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], default='New Meeting', max_length=25),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_user_updated_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
