# Generated by Django 5.0.1 on 2026-05-06 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admedabad', '0012_remove_meeting_meeting_from_followup_meeting_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='meeting_date',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='meeting_from',
        ),
        migrations.AlterField(
            model_name='followup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_assigned', to='admedabad.staff'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='admedabad.ahmedabadcompany'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ahmedabad_followup_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup',
            name='real_estate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='admedabad.ahmedabadrealestategmb'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='admedabad.ahmedabadresponse'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('New Followup', 'New Followup'), ('Re Followup', 'Re Followup'), ('Cancelled', 'Cancelled'), ('Deal Done', 'Deal Done')], default='New Followup', max_length=25),
        ),
    ]
