# Generated by Django 5.0.1 on 2026-05-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admedabad', '0013_remove_followup_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahmedabadcompany',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow_Up', 'Follow Up'), ('Not_received', 'Not Received'), ('Not Interested', 'Not Interested'), ('They Will Connect', 'They Will Connect'), ('Call later', 'Call later'), ('Call Tomorrow', 'Call Tomorrow'), ('Switched Off', 'Switched Off'), ('Invalid Number', 'Invalid Number'), ('Meeting_Follow_Up', 'Meeting-Follow Up')], default='New', max_length=25),
        ),
        migrations.AlterField(
            model_name='ahmedabadrealestategmb',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('Follow Up', 'Follow Up'), ('Not Received', 'Not Received'), ('Not Interested', 'Not Interested'), ('Deal Done', 'Deal Done'), ('Meetin_Follow_Up', 'Meeting-Follow Up')], default='New', max_length=25),
        ),
        migrations.AlterField(
            model_name='ahmedabadresponse',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Meeting', 'Meeting'), ('FollowUp', 'Follow Up'), ('Not_received', 'Not Received'), ('Software_company', 'Software Company'), ('For_job', 'For Job'), ('Training', 'Training'), ('Fake_lead', 'Fake Lead'), ('Deal_close', 'Deal Close'), ('Meeting_FollowUp', 'Meeting-Follow Up')], default='New', max_length=25),
        ),
    ]
