# Generated by Django 6.0.6 on 2026-06-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_developer_alter_project_developer'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
